# Site settings
title: "CoverageHinch"
description: "I TESTED VIRAL TIKTOK LIFE HACKS THAT ACTUALLY WORK!!. Live, Work and Play at Mill Pond in Easthampton. Rule of No consideration, No contract."
url: "https://coveragehinch.github.io"  # http://localhost:4000 

title_slog: "" # Home pge slog
title_sep: "" # Home
# verification
bing: "9F9B2F63455A0E78D3DA573BC1B0BA46"
yandex: "d95f5d37bdedbb42"
google: "lNX2pT-oCOLIG2BcxV9Z5KRQlWcDeHYpkGxuVrrVWGk"
# encoding timezone
encoding: "utf-8"
timezone: UTC
# Build settings
baseurl: / # leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:slug.html
sitemap_limit: 150.0
# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"
